### ISSUE TITLE
JSON output change

### ISSUE THREAD

**Issue by sprakashg** [dncrews/angular-elastic-builder#3]
Hi,
how to change the JSON output when the rule is set, I dont want to send filter, size while forming json.
just wanted it to be .
sample json should be 
Get rules

``` json
{
  "condition": "AND",
  "rules": [
    {
      "id": "price",
      "field": "price",
      "type": "double",
      "input": "text",
      "operator": "less",
      "value": "10.25"
    },
    {
      "condition": "OR",
      "rules": [
        {
          "id": "category",
          "field": "category",
          "type": "integer",
          "input": "select",
          "operator": "equal",
          "value": "2"
        },
        {
          "id": "category",
          "field": "category",
          "type": "integer",
          "input": "select",
          "operator": "equal",
          "value": "1"
        }
      ]
    }
  ]
}
```

**Comment by dncrews** [comment]
I keep coming back to this, but I don't understand what the question is. I've been putting off too long saying so, and now it's been way to long to be helpful to you. If this is still a question, say so, and I'll see if I can help.

**Comment by sprakashg** [comment]
Hi Dan,
Sorry, could not respond to this on time.
Initially, I had issues in integrating the plugin with business use-case.
The JSON output has to match the way it's in server side, I had to figure out, how it can be done.
Then, I figured out during the integration process, how the plugin is working internally.
