### ISSUE TITLE
checkboxes (for type multi) are deselected when query is parsed

### ISSUE THREAD

**Issue by oguennec** [dncrews/angular-elastic-builder#5]
@dncrews : When query is parsed multi values in query group are now converted to false whereas they should be converted to true so the checkboxes show as checked.
This regression has been introduced with commit e79a94b.

**Comment by tienvx** [comment]
I can confirm that this will be fixed by the commit of @oguennec

**Comment by ohneworte** [comment]
Is #5 truly fixed? It's still not working for me and also not in the demo (http://dncrews.com/angular-elastic-builder/examples) where test.state.multi is filled with:

```
{
  'terms': {
    'test.state.multi': [ 'AZ', 'CT' ]
  }
}
```

**Comment by dncrews** [comment]
@ohneworte I forgot to update the example at that time. Can you reverify?

**Comment by ohneworte** [comment]
@dncrews, sorry, but I don't see any changes - should I? In the demo of your website (http://dncrews.com/angular-elastic-builder/examples) the checkboxes in "test.state.multi" are still empty, although initialized differently (see http://dncrews.com/angular-elastic-builder/examples/exampleApp.js).
